// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

export const SUPABASE_URL = "https://zmoubbtnzffpvdjhnbxg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inptb3ViYnRuemZmcHZkamhuYnhnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ1Njg5ODIsImV4cCI6MjA3MDE0NDk4Mn0.HsnosAWMperDILZGNILIzF-MgQmeSE2JbrNvqqf8Kn8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});